[package]
name = "ice"
version = "0.0.2"
edition = "2021"
authors = ["tamton-aquib <aquibjavedt007@gmail.com>"]

[dependencies]
hex = "0.4.3"
base64 = "0.20"
base32 = "0.4"
regex = "1.6"
atty = "0.2"

[profile.release]
opt-level = "z"
strip = true
lto = true
codegen-units = 1
