[package]
name = "ice"
version = "0.0.1"
edition = "2021"

[dependencies]
hex = "0.4.3"
base64 = "0.13.0"
base32 = "0.4.0"

[profile.release]
opt-level = "z"
strip = true
lto = true
codegen-units = 1
